### PR TITLE
Fixed Reading from Primary and Secondary APPS

### LINKED ISSUE #667: Test Io Code for the primary and secondary APPS with hardware
### Summary
We need to test our Io functions for the primary and secondary APPS with the Scancon 2RMHF encoders

### Deliverables
- [ ] Check that we can use our Io functions to get the correct encoder counter values for the primary and secondary APPS

### PR DESCRIPTION
**Pull request by gtaharaedmonds**
### Summary
Tweaked steering angle config, got APPS/SAPPS firmware working on the car, modified APPS/SAPPS reset behaviour.
Note that the SAPPS is the Scancon 2RMHF-3600, and the PAPPS is the AEDL-5810-Z12 since the other Scancon encoders are broken.

### Changelist 
- Changed steering angle min/max angle and offset.
- Changed FSM encoder settings in Cube: Changed encoder mode to TI1 (counts x2 per rising edge on TIMx_CH1), changed prescaler to mode 1 (divide by 2), increased AUTO_RELOAD_REGs (the maximum values which will cause the encoder counter to reset). 
- Added "reset thresholds" so the values that the counters reset at is greater than the max pedal press value. Previously the counters reset at any value over the max pedal press which made me worried they might accidentally reset if someone fully pressed the pedal. 
- Fixed unit tests.
- Removed alarm detection for PAPPs since the new PAPPS sensor doesn't have an alarm output. Super hacky fix, Io_AcceleratorPedals_IsPappsEncoderAlarmActive just returns false constantly now.
- See notes below for detail on how these values were chosen.

### Notes on APPS parameters & their values
- Encoder mode was changed to TI1 from TI12 due to lower frequency counting. TI12 counts on edges for CH1 and CH2, whereas TI1 only counts on CH1 edges. The lower frequency counting seems more robust due to counting at a lower frequency. But truthfully this isn't a big change.
- TIMx_AUTO_RELOAD_REG: Value that the counter is automatically reset at when overflowing, and what it is set to when underflowing. Currently set to 2x a full revolution: 2x5000=10000 for PAPPS (AEDL-5810-Z12) and 2x3600=7200 for SAPPS (Scancon 2RMHF). These are pretty arbitrary, just big enough so we'll never encounter them while driving since this is not part of our desired behaviour.
- APPS_ENCODER_FULLY_PRESSED_VALUE: Counter value cooresponding to 100% full pressed pedal (minus the deadzone). Experimentally determined.
- APPS_ENCODER_RESET_VALUE: When a counter underflows, it goes from 0 to TIMx_AUTO_RELOAD_REG. Thus if we are above this threshold, we know we've underflowed since xPAPPS_ENCODER_RESET_VALUE > xAPPS_ENCODER_FULLY_PRESSED_VALUE. These are chosen to be an amount of ticks above xAPPS_ENCODER_FULLY_PRESSED_VALUE such that we'll never accidentally reset when pressing the pedal 100%.

### Testing Done
Basic testing on the car, using CAN dongle. 
Unit tests all pass.

### Resolved Issues
Resolves #667 

### Checklist
*Please change `[ ]` to `[x]` when you are ready.*
- [x] I have read and followed the code conventions detailed in [README.md](../README.md) (*This will save time for both you and the reviewer!*).
- [x] If this pull request is longer then **500** lines, I have provided *explicit* justification in the summary above explaining why I *cannot* break this up into multiple pull requests (*Small PR's are faster and less painful for everyone involved!*).

### CODE REVIEW

**Comment by pasitlaothamatas** [comment]
reminder to update any changes made in our x86 builds as well

File: boards/FSM/Src/main.c [hunk 1]
```diff
@@ -609,12 +610,12 @@ static void MX_TIM2_Init(void)
 
     /* USER CODE END TIM2_Init 1 */
     htim2.Instance               = TIM2;
-    htim2.Init.Prescaler         = 0;
-    htim2.Init.CounterMode       = TIM_COUNTERMODE_DOWN;
+    htim2.Init.Prescaler         = 1;
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/main.c:613]: are these prescalers here supposed to be 2? you mentioned how the encoder is incremented/decremented by 2

File: boards/FSM/Src/Io/Io_SteeringAngleSensor.c [hunk 2]
```diff
@@ -5,7 +5,7 @@ float Io_SteeringAngleSensor_GetAngleDegree(void)
 {
     // Steering angle = (ADC Voltage - Voltage Offset) * Degree Per Volt
 
-    const float STEERING_ANGLE_VOLTAGE_OFFSET = 1.9f;
+    const float STEERING_ANGLE_VOLTAGE_OFFSET = 1.85f;
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/Io/Io_SteeringAngleSensor.c:8]: this offset can be done with hardware, try to look into `Parameter Settings` under for this ADC in Cube

File: boards/FSM/Src/App/App_AcceleratorPedals.c [hunk 3]
```diff
@@ -28,25 +30,24 @@ struct AcceleratorPedals
...
 static float App_GetPedalPercentage(
     uint32_t encoder_fully_pressed_value,
+    uint32_t encoder_reset_value,
     uint32_t encoder_counter_value,
     void (*reset_encoder_counter)(void));
 
 static float App_GetPedalPercentage(
     uint32_t encoder_fully_pressed_value,
+    uint32_t encoder_reset_value,
     uint32_t encoder_counter_value,
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/App/App_AcceleratorPedals.c:40]: can we use a pound define in this file to specify the `encoder_fully_pressed` and `encoder_counter` values?

File: boards/FSM/Src/App/App_AcceleratorPedals.c [hunk 4]
```diff
@@ -28,25 +30,24 @@ struct AcceleratorPedals
...
     void (*reset_encoder_counter)(void))
 {
     const float percent_deflection = 0.03f;
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/App/App_AcceleratorPedals.c:43]: this can probably be a pound define

File: boards/FSM/Inc/main.h [hunk 5]
```diff
@@ -87,8 +87,8 @@ extern "C"
     (TIMx_FREQUENCY / TIM17_AUTO_RELOAD_REG / TIM17_PWM_MINIMUM_FREQUENCY)
 #define TIM3_PRESCALER 72
 #define ADC_FREQUENCY 1000
-#define TIM1_AUTO_RELOAD_REG 3599
-#define TIM2_AUTO_RELOAD_REG 1799
+#define TIM1_AUTO_RELOAD_REG 10000
```
Comment (pasitlaothamatas) [inline boards/FSM/Inc/main.h:90]: how were these values chosen?

File: boards/FSM/Src/main.c [hunk 6]
```diff
@@ -849,7 +850,7 @@ static void MX_GPIO_Init(void)
     __HAL_RCC_GPIOB_CLK_ENABLE();
 
     /*Configure GPIO pin Output Level */
-    HAL_GPIO_WritePin(GPIOA, STATUS_R_Pin | STATUS_G_Pin, GPIO_PIN_SET);
+    HAL_GPIO_WritePin(GPIOA, STATUS_R_Pin | STATUS_G_Pin, GPIO_PIN_RESET);
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/main.c:853]: u change this by accident?

File: boards/FSM/Src/main.c [hunk 7]
```diff
@@ -609,12 +610,12 @@ static void MX_TIM2_Init(void)
 
     /* USER CODE END TIM2_Init 1 */
     htim2.Instance               = TIM2;
-    htim2.Init.Prescaler         = 0;
-    htim2.Init.CounterMode       = TIM_COUNTERMODE_DOWN;
+    htim2.Init.Prescaler         = 1;
+    htim2.Init.CounterMode       = TIM_COUNTERMODE_UP;
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/main.c:614]: reminder to make one of them count down
image

File: boards/FSM/Src/App/App_AcceleratorPedals.c [hunk 8]
```diff
@@ -59,15 +60,12 @@ static float App_GetPedalPercentage(
         // low end deadzone
         return 0.0f;
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/App/App_AcceleratorPedals.c:61]: pound defines for 0.0 and 100.0 pct would be nice too

File: boards/FSM/Inc/App/configs/App_AcceleratorPedalThresholds.h [hunk 9]
```diff
@@ -2,5 +2,10 @@
 
 // TODO: Experimentally determine the encoder values for the primary and
 // secondary APPS when the accelerator is fully pressed #666
-#define PAPPS_ENCODER_FULLY_PRESSED_VALUE 900U
-#define SAPPS_ENCODER_FULLY_PRESSED_VALUE 450U
+#define PAPPS_ENCODER_FULLY_PRESSED_VALUE 2500U
```
Comment (pasitlaothamatas) [inline boards/FSM/Inc/App/configs/App_AcceleratorPedalThresholds.h:5]: i think we dont need to pass these into the apps object when we create it. we should move these #defines to App_AcceleratorPedals.c

File: boards/FSM/Src/main.c [hunk 10]
```diff
@@ -186,21 +186,21 @@ int main(void)
...
     /* USER CODE END SysInit */
 
     /* Initialize all configured peripherals */
     MX_GPIO_Init();
-    MX_DMA_Init();
     MX_CAN_Init();
     MX_IWDG_Init();
     MX_ADC2_Init();
-    MX_TIM4_Init();
+    MX_DMA_Init();
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/main.c:197]: is this from cube version thats not 5.3.0? should probably update asap lol

File: boards/FSM/Src/main.c [hunk 11]
```diff
@@ -446,7 +447,7 @@ static void MX_ADC2_Init(void)
     hadc2.Init.DataAlign             = ADC_DATAALIGN_RIGHT;
     hadc2.Init.NbrOfConversion       = 2;
     hadc2.Init.DMAContinuousRequests = ENABLE;
-    hadc2.Init.EOCSelection          = ADC_EOC_SINGLE_CONV;
+    hadc2.Init.EOCSelection          = ADC_EOC_SEQ_CONV;
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/main.c:450]: this changed by accident too?

File: boards/FSM/Src/App/App_AcceleratorPedals.c (hunk 4 above)
Comment (pasitlaothamatas) [reply boards/FSM/Src/App/App_AcceleratorPedals.c:43]: actually lets just do this in a different PR

File: boards/FSM/Inc/App/configs/App_AcceleratorPedalThresholds.h (hunk 9 above)
Comment (pasitlaothamatas) [reply boards/FSM/Inc/App/configs/App_AcceleratorPedalThresholds.h:5]: but yeah as mentioned earlier, lets take care of this on another PR

File: boards/FSM/Src/main.c (hunk 1 above)
Comment (gtaharaedmonds) [reply boards/FSM/Src/main.c:613]: Yea when testing 1 was what actually worked properly. Think it's because of this: 
image
So it's actually index 1 which is divide by 2. Is there a better way to show this in cube?

File: boards/FSM/Src/App/App_AcceleratorPedals.c (hunk 3 above)
Comment (gtaharaedmonds) [reply boards/FSM/Src/App/App_AcceleratorPedals.c:40]: fully pressed + reset value are currently defined in FSM\Inc\App\configs\App_AcceleratorPedalThresholds.h

File: boards/FSM/Inc/main.h (hunk 5 above)
Comment (gtaharaedmonds) [reply boards/FSM/Inc/main.h:90]: they're equal to 2x full revolution. choice was pretty arbitrary since we never want to auto reload, just big enough so it'll never happen in the car

File: boards/FSM/Src/main.c (hunk 6 above)
Comment (gtaharaedmonds) [reply boards/FSM/Src/main.c:853]: yep

File: boards/FSM/Src/main.c (hunk 10 above)
Comment (gtaharaedmonds) [reply boards/FSM/Src/main.c:197]: lol wtf i'm using 5.3 now :///

File: boards/FSM/Src/main.c (hunk 11 above)
Comment (gtaharaedmonds) [reply boards/FSM/Src/main.c:450]: yep

File: boards/FSM/Src/Io/Io_SteeringAngleSensor.c (hunk 2 above)
Comment (gtaharaedmonds) [reply boards/FSM/Src/Io/Io_SteeringAngleSensor.c:8]: to me it seems clearer to do offset via code, is there a reason to do in cube?

File: boards/FSM/Src/main.c (hunk 10 above)
Comment (gtaharaedmonds) [reply boards/FSM/Src/main.c:197]: i remeber you did something where you fully reload the auto-generated code. we can try that but can't remember how at the moment

File: boards/FSM/Src/main.c (hunk 1 above)
Comment (pasitlaothamatas) [reply boards/FSM/Src/main.c:613]: Ah ok that's fine then

File: boards/FSM/Src/Io/Io_SteeringAngleSensor.c (hunk 2 above)
Comment (pasitlaothamatas) [reply boards/FSM/Src/Io/Io_SteeringAngleSensor.c:8]: Less work done by software, more work done by peripheral so it's better to use thr HW offset

File: boards/FSM/Src/main.c (hunk 10 above)
Comment (pasitlaothamatas) [reply boards/FSM/Src/main.c:197]: Yeah try doing a clean build

File: boards/FSM/Src/App/App_AcceleratorPedals.c (hunk 4 above)
Comment (pasitlaothamatas) [reply boards/FSM/Src/App/App_AcceleratorPedals.c:43]: ok i remember how this works now, ignore this comment

File: boards/FSM/Src/App/App_AcceleratorPedalSignals.c [hunk 12]
```diff
@@ -109,4 +110,4 @@ void App_AcceleratorPedalSignals_AppsAndBrakePlausibilityFailureCallback(
     App_CanTx_SetPeriodicSignal_PLAUSIBILITY_CHECK_HAS_FAILED(
         can_tx,
         CANMSGS_FSM_MOTOR_SHUTDOWN_ERRORS_PLAUSIBILITY_CHECK_HAS_FAILED_TRUE_CHOICE);
-}
+}
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/App/App_AcceleratorPedalSignals.c:113]: new line

File: boards/FSM/Src/App/App_SetPeriodicCanSignals.c [hunk 13]
```diff
@@ -136,7 +137,7 @@ void App_SetPeriodicSignals_AcceleratorPedal(const struct FsmWorld *world)
     else
     {
         App_CanTx_SetPeriodicSignal_MAPPED_PEDAL_PERCENTAGE(
-            can_tx, papps_pedal_percentage);
+            can_tx, sapps_pedal_percentage); // Todo: Change back to papps
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/App/App_SetPeriodicCanSignals.c:140]: Can you make an issue as a reminder for this

File: boards/FSM/Inc/main.h (hunk 5 above)
Comment (pasitlaothamatas) [reply boards/FSM/Inc/main.h:90]: Note: the auto reload register is specifying the maximum value that can be read by the encoder before overflowing (approx 2x bigger than the full revolution of the encoder). This gives us a safe (large) range to detect underflow and reset the encoder

File: boards/FSM/Src/App/App_AcceleratorPedalSignals.c [hunk 14]
```diff
@@ -90,6 +90,7 @@ bool App_AcceleratorPedalSignals_HasAppsAndBrakePlausibilityFailure(
                25.0f;
 }
 
+// TODO: What?
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/App/App_AcceleratorPedalSignals.c:93]: lets remove this

File: boards/FSM/Src/App/App_AcceleratorPedals.c [hunk 15]
```diff
@@ -3,6 +3,20 @@
...
+#define SAPPS_ENCODER_FULLY_PRESSED_VALUE 1800U
+
+// If encoder exceeds the following values, we reset it back to zero (usually
+// due to underflowing)
+#define PAPPS_ENCODER_RESET_VALUE 3500U
+#define SAPPS_ENCODER_RESET_VALUE 2400U
+
+#define HUNDRED_PERCENT 100.0f
+#define ZERO_PERCENT 0.0f
+#define PERCENT_DEFLECTION 0.03f
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/App/App_AcceleratorPedals.c:18]: make sure you put `#define` around braces

```suggestion
#define PAPPS_ENCODER_FULLY_PRESSED_VALUE (2500U)
#define SAPPS_ENCODER_FULLY_PRESSED_VALUE (1800U)

// If encoder exceeds the following values, we reset it back to zero (usually
// due to underflowing)
#define PAPPS_ENCODER_RESET_VALUE (3500U)
#define SAPPS_ENCODER_RESET_VALUE (2400U)

#define MAX_PEDAL_PERCENTAGE (100.0f)
#define MIN_PEDAL_PERCENTAGE (0.0f)
#define PEDAL_DEFLECTION_PERCENTAGE (0.03f)
```

File: boards/FSM/Src/Io/Io_SteeringAngleSensor.c (hunk 2 above)
Comment (pasitlaothamatas) [reply boards/FSM/Src/Io/Io_SteeringAngleSensor.c:8]: lets do this in a later PR though

File: boards/FSM/Src/main.c (hunk 10 above)
Comment (pasitlaothamatas) [reply boards/FSM/Src/main.c:196]: make sure this is fixed after rebuilding

File: boards/FSM/Src/main.c [hunk 16]
```diff
@@ -560,13 +558,13 @@ static void MX_TIM1_Init(void)
...
     htim1.Instance               = TIM1;
-    htim1.Init.Prescaler         = 0;
+    htim1.Init.Prescaler         = 1;
     htim1.Init.CounterMode       = TIM_COUNTERMODE_UP;
     htim1.Init.Period            = TIM1_AUTO_RELOAD_REG;
     htim1.Init.ClockDivision     = TIM_CLOCKDIVISION_DIV1;
     htim1.Init.RepetitionCounter = 0;
     htim1.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
-    sConfig.EncoderMode          = TIM_ENCODERMODE_TI12;
+    sConfig.EncoderMode          = TIM_ENCODERMODE_TI1;
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/main.c:567]: noticed that the encoder mode here is changed, what does this change represent?

File: boards/FSM/FSM.ioc [hunk 17]
```diff
@@ -2,8 +2,9 @@
...
 ADC2.Channel-1\#ChannelRegularConversion=ADC_CHANNEL_3
 ADC2.DMAContinuousRequests=ENABLE
+ADC2.EOCSelection=ADC_EOC_SINGLE_CONV
 ADC2.ExternalTrigConv=ADC_EXTERNALTRIGCONV_T3_TRGO
-ADC2.IPParameters=Rank-0\#ChannelRegularConversion,Channel-0\#ChannelRegularConversion,SamplingTime-0\#ChannelRegularConversion,OffsetNumber-0\#ChannelRegularConversion,Offset-0\#ChannelRegularConversion,NbrOfConversionFlag,ExternalTrigConv,NbrOfConversion,DMAContinuousRequests,Rank-1\#ChannelRegularConversion,Channel-1\#ChannelRegularConversion,SamplingTime-1\#ChannelRegularConversion,OffsetNumber-1\#ChannelRegularConversion,Offset-1\#ChannelRegularConversion,SubFamily
+ADC2.IPParameters=Rank-0\#ChannelRegularConversion,Channel-0\#ChannelRegularConversion,SamplingTime-0\#ChannelRegularConversion,OffsetNumber-0\#ChannelRegularConversion,Offset-0\#ChannelRegularConversion,NbrOfConversionFlag,ExternalTrigConv,NbrOfConversion,DMAContinuousRequests,Rank-1\#ChannelRegularConversion,Channel-1\#ChannelRegularConversion,SamplingTime-1\#ChannelRegularConversion,OffsetNumber-1\#ChannelRegularConversion,Offset-1\#ChannelRegularConversion,SubFamily,EOCSelection
```
Comment (pasitlaothamatas) [inline boards/FSM/FSM.ioc:7]: what is this extra `EOCSelection` for?

File: boards/FSM/FSM.ioc [hunk 18]
```diff
@@ -225,10 +226,9 @@ PA6.GPIO_Label=BRAKE_PRESS_BUFF
 PA6.Locked=true
 PA6.Mode=IN3-Single-Ended
 PA6.Signal=ADC2_IN3
-PA7.GPIOParameters=PinState,GPIO_Label
+PA7.GPIOParameters=GPIO_Label
 PA7.GPIO_Label=STATUS_G
 PA7.Locked=true
-PA7.PinState=GPIO_PIN_SET
```
Comment (pasitlaothamatas) [inline boards/FSM/FSM.ioc:231]: Seems to be a change with the pin state here, can you make sure that we change this back to what it was before

Comment (pasitlaothamatas) [reply boards/FSM/FSM.ioc:231]: not sure if these are introduced by u or by cube lol

**Comment by pasitlaothamatas** [comment]
looks like unit test stuff is still broken. Run FsmTest on ur build to see if stuffs broken before you push

File: boards/FSM/Src/main.c (hunk 16 above)
Comment (gtaharaedmonds) [reply boards/FSM/Src/main.c:567]: TI12 counts up on rising edge on TIM2_CH1 or TIM2_CH2
TI1 counts up only on rising edge on TIM2_CH1
Felt like the latter made more sense and would be less noise-sensitive

File: boards/FSM/FSM.ioc (hunk 17 above)
Comment (gtaharaedmonds) [reply boards/FSM/FSM.ioc:7]: Not sure. I'm assuming this was added when I changed ADC2's EOC back to single conversion as per previous comment.

File: boards/FSM/Src/main.c (hunk 16 above)
Comment (timbitss) [reply boards/FSM/Src/main.c:567]: Just to be complete, I think TI1 means to count up/down on the rising/falling edge of TI1 based on the value of TI2.

File: boards/FSM/Src/main.c (hunk 1 above)
Comment (timbitss) [reply boards/FSM/Src/main.c:610]: Could you update this in the PR description?

File: boards/FSM/Inc/App/App_AcceleratorPedals.h [hunk 19]
```diff
@@ -2,6 +2,20 @@
 
 #include <stdbool.h>
 
+// TODO: Experimentally determine the encoder values for the primary and
+// secondary APPS when the accelerator is fully pressed #666
+#define PAPPS_ENCODER_FULLY_PRESSED_VALUE (2500U)
+#define SAPPS_ENCODER_FULLY_PRESSED_VALUE (1800U)
+
+// If encoder exceeds the following values, we reset it back to zero (usually
+// due to underflowing)
```
Comment (timbitss) [inline boards/FSM/Inc/App/App_AcceleratorPedals.h:11]: Could we also add in the comments something like "E.g accelerator pedal pressed when FSM boots up"

File: boards/FSM/Inc/App/configs/App_SteeringAngleThresholds.h [hunk 20]
```diff
@@ -4,5 +4,5 @@
 // TODO: Calculate the new steering angle's voltage offset as well as the upper
 // and lower limits (#602)
 
-#define MIN_STEERING_ANGLE_DEG -110.0f
-#define MAX_STEERING_ANGLE_DEG 110.0f
+#define MIN_STEERING_ANGLE_DEG -130.0f
+#define MAX_STEERING_ANGLE_DEG 130.0f
```
Comment (pasitlaothamatas) [inline boards/FSM/Inc/App/configs/App_SteeringAngleThresholds.h:8]:
```suggestion
#define MIN_STEERING_ANGLE_DEG (-130.0f)
#define MAX_STEERING_ANGLE_DEG (130.0f)
```

File: boards/FSM/Src/Io/Io_AcceleratorPedals.c [hunk 21]
```diff
@@ -4,9 +4,11 @@
 
 bool Io_AcceleratorPedals_IsPappsEncoderAlarmActive(void)
 {
-    return HAL_GPIO_ReadPin(
-               PRIMARY_APPS_ALARM_GPIO_Port, PRIMARY_APPS_ALARM_Pin) ==
-           GPIO_PIN_SET;
+    //    return HAL_GPIO_ReadPin(
+    //               PRIMARY_APPS_ALARM_GPIO_Port, PRIMARY_APPS_ALARM_Pin) ==
+    //           GPIO_PIN_SET;
+
```
Comment (pasitlaothamatas) [inline boards/FSM/Src/Io/Io_AcceleratorPedals.c:10]:
```suggestion

```

Comment (pasitlaothamatas) [reply boards/FSM/Src/Io/Io_AcceleratorPedals.c:10]: lets clean this up in a future PR, can you make an issue for this? @gtaharaedmonds

File: boards/FSM/Src/main.c (hunk 10 above)
Comment (pasitlaothamatas) [reply boards/FSM/Src/main.c:196]: Bump

File: boards/FSM/Inc/App/App_AcceleratorPedals.h [hunk 22]
```diff
@@ -2,6 +2,20 @@
...
+#define PAPPS_ENCODER_RESET_VALUE (3500U)
+#define SAPPS_ENCODER_RESET_VALUE (2400U)
+
+#define HUNDRED_PERCENT (100.0f)
+#define ZERO_PERCENT (0.0f)
```
Comment (pasitlaothamatas) [inline boards/FSM/Inc/App/App_AcceleratorPedals.h:16]:
```suggestion
#define MAX_ACC_PEDAL_PERCENT (100.0f)
#define MIN_ACC_PEDAL_PERCENT (0.0f)
```

File: boards/FSM/Test/Src/Test_StateMachine.cpp [hunk 23]
```diff
@@ -284,7 +280,7 @@ class FsmStateMachineTest : public BaseStateMachineTest
         uint8_t   true_choice,
         uint8_t   false_choice)
     {
-        for (size_t pedal_percentage = 10; pedal_percentage <= 100;
+        for (size_t pedal_percentage = 11; pedal_percentage <= 100;
```
Comment (pasitlaothamatas) [inline boards/FSM/Test/Src/Test_StateMachine.cpp:283]: lets try to get rid of these magic numbers if possible, can u do this for the current PR?

**Review by gtaharaedmonds — COMMENTED** [review]
review done

**Review by pasitlaothamatas — APPROVED** [review]
image
